### ISSUE TITLE
Add coloredmanga extension in saikou

### ISSUE THREAD

**Issue by KunalSucks** [saikou-app/saikou#520] opened 2023-01-24 20:16 UTC
### Summary

I want a new enxtension which is colored manga. you can see it on google

### The Problem

Add it pleaseeeee

### The Ideal Solution

Please add it

**Comment by Adolar0042** [comment] 2023-01-24 20:21
Some sources already provide colored versions. You can find them by using "Wrong Title?" (Most of the time the name format for them is `<title> (colored)`)

**Comment by scrazzz** [comment] 2023-01-24 20:32
Duplicate of #462

**Closed by scrazzz** 2023-01-24 20:32 UTC
Labels: enhancement
