### ISSUE TITLE
Allow Custom Download Location

### ISSUE THREAD

**Issue by lonewolf0211** [saikou-app/saikou#365] opened 2022-08-22 18:31 UTC
### Summary

There is already an option to select your SD card as a download location, I would like to see the download path become customizable.

### The Problem

There is already an option to select your SD card as a download location but it defaults to the android folder which most apps like VLC won't be able to access even after giving said app the "all files" permission. Which means that I have to relocate the files to a readable location for VLC to work. 

I'm not sure if it's a bug or related to file permissions but I have also had several downloads in the Saikou app folder stored on my SD card go missing.

### The Ideal Solution

I would like the download path to become customizable so the files could be downloaded directly into a readable folder.  

### The Current Solution

I have to move the files manually.

**Comment by brahmkshatriya** [comment] 2022-08-24 11:31
duplicate of #15

**Closed by brahmkshatriya** 2022-08-24 11:31 UTC
Labels: enhancement
