### ISSUE TITLE
Site request: YugenAnime

### ISSUE THREAD

**Issue by rollingmoai** [saikou-app/saikou#494] opened 2023-01-03 02:03 UTC
### Summary

Add YugenAnime as an alternative for Animixplay

### The Problem

Since Animixplay is down, YugenAnime is recommended as a great Animixplay alternative that can also scrape Gogo and VRV.

### The Ideal Solution

Add YugenAnime

### Additional Context

https://yugen.to/

**Comment by scrazzz** [comment] 2023-01-03 03:50
Duplicate of #115

**Closed** 2023-01-03 03:50 UTC
Labels: enhancement
