### ISSUE TITLE
every anime source is not working: showing error when stream

### ISSUE THREAD

**Issue by gyro77** [saikou-app/saikou#565] opened 2023-02-20 18:49 UTC
### Summary

every anime source except zoro and gogo doesn't even load anime, and the rest 2 (zoro and gogo) show error when clicked on video, saying some type of error.

### Reproduction Steps

as i said all the sources except zoro and gogo DOES NOT even load anime, saying no source found
and zoro and gogo shows anime but doesn't stream
zoro and gogo may stream one episode when closing it and restarting it after a long time, but then shows no stream source found and you know the rest

### Expected Result

all sources should work properly, if not, then there's no reason for those to be on the app.

### Actual Result

doesn't stream.
its frustrating, really.

### Device Information

saikou version :- 1.2.0,24
brand- oppo reno 2f
architecture- arm64-v8a
android- 11

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

allanime has moved ig, so changing source url should fix the issue about allanime.
some sources may have expired...
in any way, all these source issues should be fixed cause its a problem.
i just want the app to be better :)

**Comment by Adolar0042** [comment] 2023-02-20 18:58
Duplicate of #559

**Closed by Adolar0042** 2023-02-20 18:58 UTC
Labels: bug

**Comment by sjain3097** [comment] 2023-02-21 14:38
Do we need to update the app for this? It's still happening in my app
