### ISSUE TITLE
not all tags are shown

### ISSUE THREAD

**Issue by DemonLordDiablo** [saikou-app/saikou#338] opened 2022-07-29 01:31 UTC
### Summary

some tags that are shown on anilist, but not in the app.

### Reproduction Steps

go to [Oshi no Ko] on app and anilist
on anilist the tag tsundere is there mut not in the app
some other tags are also hidden too.

### Expected Result

all tags should allways be visiable

### Actual Result

some tags were hidden

### Device Information

Saikou Version: 1.2.0.17
Device: samsung gtexswifi
Architecture: arm
OS Version: REL 5.1.1 (22)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

i would also like to have a way to search for both adault and non adault manga/anime at the same time.

**Comment by brahmkshatriya** [comment] 2022-07-29 11:24
duplicate of #146

**Closed by brahmkshatriya** 2022-07-29 11:24 UTC
Labels: bug

**Comment by DemonLordDiablo** [comment] 2022-08-08 03:14
can you tell my why this was marked as a duplicate? it seems different then the other question.

**Comment by brahmkshatriya** [comment] 2022-08-08 06:10
reworking search will have all tags

**Comment by DemonLordDiablo** [comment] 2022-08-09 03:44
oh, okay.
