### ISSUE TITLE
Option to select subtitles manually. 

### ISSUE THREAD

**Issue by soymadip** [saikou-app/saikou#252] opened 2022-06-11 03:37 UTC
### Summary

Some providers like Gogo Don't have subtitles at dubbed anime. So it will be major help to be able to select subtitles manually.

### The Problem

No  subtitle at dubbed anime by default.

### The Ideal Solution

To add a manual subtitle picker.
I got the idea from a similar project :- [Cloudstream -3](https://github.com/LagradOst /CloudStream-3) 

Also I took a screenshot for general idea;- 
![Screenshot-Cloudstream-Subtitle_picker](https://user-images.githubusercontent.com/84225810/173170816-99b38d3f-cbef-400f-bf6f-86bca2c055ad.jpg)

### The Current Solution

Nothing, you have to rely on provider.

### Additional Context

I wanna add that 3rd party subtitle providers like  openSubtitles.org also can be added to search subtitles.

**Comment by brahmkshatriya** [comment] 2022-06-11 06:02
Duplicate of #64

**Closed by brahmkshatriya** 2022-06-11 06:02 UTC
Labels: enhancement
