### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Tric0w0** [saikou-app/saikou#561] opened 2023-02-19 12:04 UTC
### Summary

All source are showing error.

### Reproduction Steps

Open any show and select the Zoro source.

### Expected Result

Episodes should show and at least the streamsb source should come up.

### Actual Result

Nothing, simply shows couldn't find anything. Using wrong title doesn't work either as nothing appears for the search.

### Device Information

Saikou Version: 1.2.0.24
Device: vivo 2034
Architecture: aarch64
OS Version: REL 11 (30)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Please clear this bug as fast as you can.

**Comment by brahmkshatriya** [comment] 2023-02-19 14:37
duplicate of #559

**Closed by brahmkshatriya** 2023-02-19 14:37 UTC
Labels: bug
