### ISSUE TITLE
Add frame capture/screenshot support (Inspired by the now dead AnyWatch.me)

### ISSUE THREAD

**Issue by pseudokawaii** [saikou-app/saikou#418] opened 2022-10-08 07:59 UTC
### Summary

Feature to capture any frame while playing/paused.

### The Problem

Still frames have many uses in the anime community (like making memes and sharing on social media), but it's very inconvenient to capture the frames using the traditional screenshot feature. A few drawbacks of the traditional method is ~
- It also captures the black bars outside the frame.
- It can't capture a frame with the original aspect ratio.
- It also captures external subtitles with the frame.
- Reduces the frame quality.

### The Ideal Solution

A feature to capture any frame while the video is playing or paused would be nice. There should be a button within the player for this. The feature should only capture the frame with it's original aspect ratio and resolution intact.

**Comment by scrazzz** [comment] 2022-10-08 08:15
Duplicate of #275

**Closed by scrazzz** 2022-10-08 08:15 UTC
Labels: enhancement
