### ISSUE TITLE
Empty Server list

### ISSUE THREAD

**Issue by NeoS4ma** [saikou-app/saikou#666] opened 2023-05-01 21:08 UTC
### Summary

Trying to watch an anime but there's no server showing up

### Reproduction Steps

When i select any episode the app shows an empty server list

### Expected Result

There should be a list of server appearing when selecting an episode.

### Actual Result

There's no server listed

### Device Information

Saikou Version: 1.2.2.1
Device: Redmi sunny
Architecture: aarch64
OS Version: REL 11 (30)

### Checklist

- [x] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment] 2023-05-04 12:41
Duplicate of #661

**Closed by brahmkshatriya** 2023-05-04 12:41 UTC
Labels: bug
