### ISSUE TITLE
Android TV Remote Support

### ISSUE THREAD

**Issue by rahaaatul** [saikou-app/saikou#316] opened 2022-07-13 08:26 UTC
### Summary

Add remote support to scroll up/down or left/right and other options.

### The Problem

• You can't select anything with remote in Saikou UI.
• There's no indicator/focus if something is selected or not.
• In Manga reading, you can't scroll up/down or left/right with remote.

### The Ideal Solution

Add remote buttons:

| ACTION | KEYCODE     |
|--------|-------------|
| Select | DPAD_CENTER |
| Up     | DPAD_UP     |
| Down   | DPAD_DOWN   |
| Left   | DPAD_LEFT   |
| Right  | DPAD_RIGHT  |
| Menu   | MENU        |

Found in - `/system/usr/keylayout/Vendor_XXXX_Product_XXXX_Version_XXXX.kl`

For more Keycodes - https://android.googlesource.com/platform/frameworks/base/+/ccbf84f/data/keyboards/Generic.kl

### The Current Solution

Use Mouse.

### Additional Context

This would be a great function for TV users. This would help us a lot. Thank you.

**Comment by Adolar0042** [comment] 2022-07-13 08:37
There is a fork with tv support (found it on the Saikou Discord server, so can prob. be trusted)

https://github.com/Nanoc6/SaikouTV/

**Comment by brahmkshatriya** [comment] 2022-07-13 11:18
Duplicate of #3

**Closed by brahmkshatriya** 2022-07-13 11:18 UTC
Labels: enhancement
