### ISSUE TITLE
Animepahe source not working 

### ISSUE THREAD

**Issue by Arpitvv** [saikou-app/saikou#548] opened 2023-02-15 06:17 UTC
### Summary

Now even Animepahe is not working 

### Reproduction Steps

Fix it

### Expected Result

Just fix it please

### Actual Result

Idk

### Device Information

Idc

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by scrazzz** [comment] 2023-02-15 07:17
Duplicate of #546

**Closed by scrazzz** 2023-02-15 07:17 UTC
Labels: bug
