### ISSUE TITLE
bulk download feature please ?

### ISSUE THREAD

**Issue by vellankiindeevar** [saikou-app/saikou#307] opened 2022-07-09 10:08 UTC
### Summary

bulk download feature would be helpful

### The Problem

bulk download feature would be helpful to get all the anime 

### The Ideal Solution

the ideal solution would be scraping from any torrented servies for anime or something

**Comment by brahmkshatriya** [comment] 2022-07-09 10:33
duplicate of #15 
mf refuses to see all issues 💀

**Closed by brahmkshatriya** 2022-07-09 10:33 UTC
Labels: enhancement
