### ISSUE TITLE
Download Manga feature 

### ISSUE THREAD

**Issue by SispTheGamer** [saikou-app/saikou#472] opened 2022-12-04 11:05 UTC
### Summary

Adding a download Manga feature would be great for this app.

### The Problem

I thought that an option to download Manga should be added because this feature would be great and the competitor app (Aniyomi) have this feature so it would be great if you add download Manga feature to this app. 

### The Ideal Solution

Just to add a download icon on the top right corner in the "read" section (tab) then if you also can (optional), an option for choosing the chapters we want to download and to add an option to download unread chapters. I know I'm asking a lot but it would make the app a lot better if this feature is implemented to this app.

**Comment by scrazzz** [comment] 2022-12-04 11:09
Duplicate of #15

**Closed by scrazzz** 2022-12-04 11:09 UTC
Labels: enhancement
