### ISSUE TITLE
Hide watched series and manga when searching 

### ISSUE THREAD

**Issue by Rahimime** [saikou-app/saikou#553] opened 2023-02-16 19:00 UTC
### Summary

Hide in search , things i watched already.

### The Problem

Just came here to suggest add an option when searching , anime or mangas that are already on my list dont show up or gray out , so i can see only new ones , thank you .
I think its an essencial future and everyone will love it.

### The Ideal Solution

Hide things that are on my listed .

**Comment by scrazzz** [comment] 2023-02-16 19:49
Duplicate of #549

**Closed by scrazzz** 2023-02-16 19:49 UTC
Labels: enhancement
