### ISSUE TITLE
Continues reeding

### ISSUE THREAD

**Issue by XxMCBxX** [saikou-app/saikou#70] opened 2022-03-24 12:27 UTC
Is there going to be a way to just reed manga continuesly, like rn when i finish a chapter i have to close out of the chapter thene check it as read and thene open a new chapter thene again. Pls add a fix for that.

Thank you.

**Comment by XxMCBxX** [comment] 2022-03-24 12:28
And i hope there will be a way if you do add the continues reedi that you dont have to maualy check that the chapter is read.

**Comment by brahmkshatriya** [comment] 2022-03-24 12:34
duplicate of #18

**Closed by brahmkshatriya** 2022-03-24 12:34 UTC
