### ISSUE TITLE
Merge Title

### ISSUE THREAD

**Issue by vamshidhar1211** [saikou-app/saikou#615] opened 2023-03-23 11:43 UTC
### Summary

Option to merge title's

### The Problem

Some anime in anilist like jojo bizzare adventure season 6 part 2 has 26 episodes but whereas in streaming sources jojo season 6 part 2 is divided as part 2 and 3 .It is great if there is feature to merge title.

### The Ideal Solution

option to merge two title's into one title

**Comment by scrazzz** [comment] 2023-03-23 12:20
Unfortunately, since this is a specific issue with this anime it won't be fixed. Also, we can't change the data that we get from AniList and from other sources. Use the "Wrong Title" option and choose the correct season/title.

**Closed by scrazzz** 2023-03-23 12:20 UTC
Labels: enhancement

**Comment by vamshidhar1211** [comment] 2023-03-23 13:05
it's not with specific anime there are other manga/anime which helps with this feature

**Comment by scrazzz** [comment] 2023-03-23 14:35
> it's not with specific anime there are other manga/anime which helps with this feature

Use the 'Wrong Title' option.

**Comment by vamshidhar1211** [comment] 2023-03-23 15:29
> > it's not with specific anime there are other manga/anime which helps with this feature
> 
> Use the 'Wrong Title' option.

for example if i watch jojo season 6 part 2 the anilist has tracking of 26 episodes but the streaming source has only 12 episode of part 2 and another 14 episodes are divided has part 3
now if i watch part 2 all episode progress is updated as 12 if i change the title to part 3 the progress of anime move to 14 episode by watching all the episodes of part 3 but not as progress to 26 episodes.
if there is option to merge title the part 2 and part 3 will be combined to make 26 episode so that progress is made correctly.

i hope you get my whole point

**Comment by 5H4D0WILA** [comment] 2023-03-23 16:02
the issue is not that the devs dont understand your point.
its just not feasible/possible to fix, as its provider and anime specific

**Comment by vamshidhar1211** [comment] 2023-03-23 16:47
Thank you
