### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XxMCBxX** [saikou-app/saikou#364] opened 2022-08-20 21:32 UTC
### Summary

Cant watch anime and text shows that there is a error in the code

### Reproduction Steps

Opened anime in 9anime.

### Expected Result

Episodes to show.

### Actual Result

![Screenshot_2022-08-20-23-27-00-287_ani saikou beta](https://user-images.githubusercontent.com/87391230/185766565-415397f1-6bba-4d4b-892a-138eaaf9be98.jpg)

### Device Information

Saikou Version: 1.2.0.17
Device: Redmi spesn
Architecture: aarch64
OS Version: REL 11 (30)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

I didnt search for duplicates i just checked it so i can post this.

**Comment by riimuru** [comment] 2022-08-21 00:54
@XxMCBxX what do you mean you cant watch anime, what happened to the other providers? also this is a duplicate.

**Comment by yutubeare456** [comment] 2022-08-21 01:35
> ### Summary
> Cant watch anime and text shows that there is a error in the code
> 
> ### Reproduction Steps
> Opened anime in 9anime.
> 
> ### Expected Result
> Episodes to show.
> 
> ### Actual Result
> ![Screenshot_2022-08-20-23-27-00-287_ani saikou beta](https://user-images.githubusercontent.com/87391230/185766565-415397f1-6bba-4d4b-892a-138eaaf9be98.jpg)
> 
> ### Device Information
> Saikou Version: 1.2.0.17 Device: Redmi spesn Architecture: aarch64 OS Version: REL 11 (30)
> 
> ### Checklist
> * [x]  I have searched the open AND closed issues for any duplicates.
> 
> ### Additional Information
> I didnt search for duplicates i just checked it so i can post this.

Yeah... I'm always experiencing it 9anime. It didn't really work for me so I changed the source to allanime it's almost the same as 9anime but it's always working.

**Comment by brahmkshatriya** [comment] 2022-08-21 06:09
duplicate of #355

**Closed by brahmkshatriya** 2022-08-21 06:09 UTC
Labels: bug
