### ISSUE TITLE
HD support on emulators

### ISSUE THREAD

**Issue by john-ioannides** [saikou-app/saikou#272] opened 2022-06-18 20:06 UTC
### Summary

HD support on emulators (like Bluestacks)

### The Problem

It seems that the app does not allow 720p or 1080p resolutions on emulators. This is quite possibly a restraint of the app.
Tried on Bluestacks 5 with the Kamyroll multiquality server.

### The Ideal Solution

If this is indeed a constraint, it could perhaps be resolved.

**Comment by scrazzz** [comment] 2022-06-18 21:07
Duplicate of #235

**Closed by scrazzz** 2022-06-18 21:07 UTC
Labels: duplicate
