### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by uShldGetCeleste** [saikou-app/saikou#478] opened 2022-12-13 00:52 UTC
### Summary

Take screenshot of current video

### The Problem

Anime have amazing art and screenshota make great wallpapers. Just in general, screenshots are nice. The problem is that just taking a screenshot with android's screenshot feature results in a lower quality image.

### The Ideal Solution

The solution would be to have a button (or maybe something like 3 finger tap?) to take a screenshot.

**Comment by Dawson908** [comment] 2022-12-13 01:02
@Adolar0042 @scrazzz @4JX @
Need fix api ![Screenshot_20221203-130109_Saikou .jpg](https://user-images.githubusercontent.com/120058459/207200611-c87d1e0d-e258-49e4-8c0c-7b86b7a72d62.jpg)

**Comment by scrazzz** [comment] 2022-12-13 05:09
Duplicate of #275

**Closed by scrazzz** 2022-12-13 05:09 UTC
Labels: enhancement
