### ISSUE TITLE
New Search features

### ISSUE THREAD

**Issue by Mrbroggle** [saikou-app/saikou#549] opened 2023-02-15 08:15 UTC
### Summary

Add search options to filter out what's in your list

### The Problem

Searching for new anime is annoying when you have already seen everything you are looking for

### The Ideal Solution

We already have the search in list options just make another button to do the inverse of thag

**Comment by brahmkshatriya** [comment] 2023-02-16 14:48
Duplicate of #511

**Closed by brahmkshatriya** 2023-02-16 14:48 UTC
Labels: duplicate, enhancement
