### ISSUE TITLE
Android TV remote not working for select things.

### ISSUE THREAD

**Issue by Fatcakes** [saikou-app/saikou#267] opened 2022-06-17 08:16 UTC
### Summary

You can't move and select anything except in the player using a the remote. I'm using a FireTV stick running the latest firmware.  Currently I'm using a Bluetooth mouse to workaround this issue.

### Reproduction Steps

Open app. Try selecting anime.

### Expected Result

To be able to select things

### Actual Result

Not being able to select things 

### Device Information

FireTV stick 4(
Fire OS 6.2 8.9
Build 6370051.1

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment] 2022-06-17 10:35
Duplicate of #3

**Closed by brahmkshatriya** 2022-06-17 10:35 UTC
Labels: bug
