### ISSUE TITLE
New Source Animixplay

### ISSUE THREAD

**Issue by Rohan-511** [saikou-app/saikou#283] opened 2022-06-28 19:45 UTC
### Summary

At the moment the app has some great sources but one of the popular website Animixplay is missing at the moment

### The Problem

The sources available currently are fast but not blazing fast like I've seen in Aniyomi (Tachiyomi Fork) Animixplay extension. 

### The Ideal Solution

Animixplay is one of the best source currently available for Aniyomi(A Tachiyomi fork for anime) with very fast response and very few loading or lagging issues.
This website is very popular so I think it would be a great addition to currently available sources. 

Webpage: animixplay.to

### The Current Solution

Using available sources like 9anime,Googoo,AllAnime, Zoro etc. 

### Additional Context

I know it's selfish of me to ask something that I'm interested in but I know this will help other people too.

Thanks for reading.

**Comment by Bilnaa** [comment] 2022-06-28 19:48
They plan to add AllAnime instead of AniMixPlay, since AllAnime has larger collection of sources

**Comment by yutubeare456** [comment] 2022-06-29 01:58
> ### Summary
> At the moment the app has some great sources but one of the popular website Animixplay is missing at the moment
> 
> ### The Problem
> The sources available currently are fast but not blazing fast like I've seen in Aniyomi (Tachiyomi Fork) Animixplay extension.
> 
> ### The Ideal Solution
> Animixplay is one of the best source currently available for Aniyomi(A Tachiyomi fork for anime) with very fast response and very few loading or lagging issues. This website is very popular so I think it would be a great addition to currently available sources.
> 
> Webpage: animixplay.to
> 
> ### The Current Solution
> Using available sources like 9anime,Googoo,AllAnime, Zoro etc.
> 
> ### Additional Context
> I know it's selfish of me to ask something that I'm interested in but I know this will help other people too.
> 
> Thanks for reading.

I requested it before but i think it's not possible because it's a simple Gogoscraper.

**Comment by yutubeare456** [comment] 2022-06-29 01:59
animixplay is a simple gogoscraper, allanime is basically an alt in saikou

**Comment by scrazzz** [comment] 2022-06-30 03:01
Duplicate of #17 #100 #166

**Closed by scrazzz** 2022-06-30 03:01 UTC
Labels: enhancement
