### ISSUE TITLE
Support for Novel Reading

### ISSUE THREAD

**Issue by MrUNKNOWNN7** [saikou-app/saikou#500] opened 2023-01-09 07:43 UTC
### Summary

Please add support for reading Light Novels.

### The Problem

Can't read the novels available in the novel section since the feature is not implemented.

### The Ideal Solution

Please add support for reading light novels as well. If I recall correctly it can be done using extensions if DMCA is concerned, without needing to host anything on the server or app. For reference, cloudstream(for streaming only) and LNReader uses extensions for the services they provide.

### The Current Solution

You can start experimenting in beta releases. If It works out, that's great. If not, well that would be a bummer but we'll also accept that.

### Additional Context

I am currently using LNReader but I really like the UI of Saikou and it's user-friendlyness in suggesting the novels I want to read, or may want to read in the future which isn't available in the app mentioned above. And I have been really enjoying the features available in Saikou as well. It's an amazing app and I thank you for creating such amazing app for people like us who really appreciate your hard work.

**Comment by scrazzz** [comment] 2023-01-09 08:00
Duplicate of #377 

It's already a planned feature.

**Closed by scrazzz** 2023-01-09 08:00 UTC
Labels: enhancement

**Comment by MrUNKNOWNN7** [comment] 2023-01-11 08:16
Glad to hear that. Can't wait to experience reading novels in Saikou.
