### ISSUE TITLE
Searched anime not showing up. 

### ISSUE THREAD

**Issue by GouravShetty** [saikou-app/saikou#455] opened 2022-11-13 16:22 UTC
### Summary

Even though I have a high speed internet connection, nothing loads when I search for something . The thing keeps showing where it says "does your internet perhaps suck?". 

### Reproduction Steps

I just close the app and open it and then there it is, the same thing. 

### Expected Result

I expected it to show the anime I searched for. 

### Actual Result

Rather than showing the anime searched for... It shows some pop-up jwerw it says "does you internet perhaps, suck?".(I have an high speed internet tho). 

### Device Information

Saikou Version: 1.2.0.23
Device: HONOR HWCAM-H
Architecture: aarch64
OS Version: REL 6.0 (23)

### Checklist

- [ ] I have searched the open AND closed issues for any duplicates.

### Additional Information

You guys are the best man. I live how you try to bring in new features, but do try and IMPROVE the existing stuff.

PEACE-

**Comment by Adolar0042** [comment] 2022-11-13 16:24
afaik the anilist api is mostly disabled due to issues right now, so you will have to wait until they resolve their problems

**Comment by scrazzz** [comment] 2022-11-13 17:41
Duplicate of #537 and some more closed issues. Next time check previous issues before opening a new one.

**Closed by scrazzz** 2022-11-13 17:41 UTC
Labels: bug
