### ISSUE TITLE
Another one Hahaha

### ISSUE THREAD

**Issue by Nevenon** [saikou-app/saikou#640] opened 2023-04-10 18:07 UTC
### Summary

It show a different kind of video instead of the anime

### Reproduction Steps

Using streamsb in Gogo When you change Video quality 

### Expected Result

It's Gogo's fault Don't need to fix right away.

### Actual Result

Wrong video showing instead of anime 

### Device Information

Saikou version 1.2.2.0
Vivo 1606
Snapdragon 425 1.4GHz
Android 6.0.1

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

![Screenshot_20230411_020233](https://user-images.githubusercontent.com/107057902/230963929-3d30458a-82c9-4137-b21b-d57fa760b3c4.jpg)
![Screenshot_20230410_004903](https://user-images.githubusercontent.com/107057902/230963954-466643dd-4a0e-4513-b539-1ce4e329a6a1.jpg)

**Comment by brahmkshatriya** [comment] 2023-04-10 19:23
No need to make new issues for it
Duplicate of #637

**Closed** 2023-04-10 19:23 UTC
Labels: bug
