### ISSUE TITLE
[Request]: Add Light Novel  Support

### ISSUE THREAD

**Issue by ABDERRAHMANE-OUALI** [saikou-app/saikou#377] opened 2022-09-04 00:58 UTC
### Summary

Add light novel reading support 

### The Problem

Can't read the light novels directly in the app, will have to download epub filea from the internet 

### The Ideal Solution

Working on adding light novel support, and I'm  also a developer and would like to participate on building the parser for light novel

**Comment by scrazzz** [comment] 2022-09-04 02:37
Duplicate of #122

**Closed** 2022-09-04 02:37 UTC
Labels: enhancement
