### ISSUE TITLE
Vidstream not showing up

### ISSUE THREAD

**Issue by kairusds** [saikou-app/saikou#795] opened 2023-08-24 22:02 UTC
### Summary

Vidstream doesn't show up on all servers that supports it.

### Reproduction Steps

Select a server then open the mirror picker menu.

### Expected Result

Vidstream mirror to be selectable for all servers that supports it.

### Actual Result

Vidstream mirror doesn't show up.

### Device Information

Saikou Version: 1.2.5.438362a
Device: POCO vayu
Architecture: aarch64
OS Version: REL 11 (30)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment] 2023-08-26 09:03
duplicate of #782

**Closed by brahmkshatriya** 2023-08-26 09:03 UTC
Labels: bug

**Comment by kairusds** [comment] 2023-08-27 18:58
> duplicate of #782

Not a duplicate and the vidstream mirror is still not showing up with the latest commit.

**Comment by Shebyyy** [comment] 2023-08-27 19:08
Showing on Gogo and kaido.
