### ISSUE TITLE
Android TV app

### ISSUE THREAD

**Issue by malekairmaroc7** [saikou-app/saikou#324] opened 2022-07-18 10:09 UTC
### Summary

Is there any plan to implement android TV support?

### The Problem

I tried using Saikou on Android TV but it (obviously) doesn't navigate through the app.

### The Ideal Solution

Adding support for Android TV

**Comment by brahmkshatriya** [comment] 2022-07-18 10:35
Duplicate of #3

**Closed by brahmkshatriya** 2022-07-18 10:35 UTC
Labels: enhancement
