### ISSUE TITLE
Anime not loading in app 

### ISSUE THREAD

**Issue by Kinu4341l** [saikou-app/saikou#665] opened 2023-05-01 13:37 UTC
### Summary

When ever i open app it get open but when loading anime ep no episode showing in the inter face 

### Reproduction Steps

Its showing this code 

java.lang.Exception: Var : {"showId":"7DkTkHkqCgiaNMmp9","episodeNumStart":0,"episodeNumEnd":5}
Error : PersistedQueryNotFound
	at ani.saikou.parsers.anime.AllAnime.graphqlQuery(AllAnime.kt:141)
	at ani.saikou.parsers.anime.AllAnime.access$graphqlQuery(AllAnime.kt:15)
	at ani.saikou.parsers.anime.AllAnime$graphqlQuery$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

### Expected Result

Fix it plz and let me know 

### Actual Result

Not showing anime episode 

### Device Information

Saikou Version: 1.2.2.1
Device: realme RMX2151L1
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Its a great app for anime manga lover 
I love this app 
I am using it from about 2 month 
Its well stable app 
Lz fix the issue that i am facing
And plz respond to it as soon as possible

**Comment by brahmkshatriya** [comment] 2023-05-04 12:40
Duplicate of #661

**Closed by brahmkshatriya** 2023-05-04 12:40 UTC
Labels: bug, duplicate

**Comment by Kinu4341l** [comment] 2023-05-05 02:45
Sir ye kya hota hai mughe nahi pata
Plz explain
