### ISSUE TITLE
Zoro and Gogo

### ISSUE THREAD

**Issue by FemanD-AI** [saikou-app/saikou#730] opened 2023-07-06 08:31 UTC
### Summary

Zoro website domain change to aniwatch and gogoanime source not working

### Reproduction Steps

When you try to open zoro it won't work and the same for gogoanime

### Expected Result

zoro source should be changed to aniwatch and gogoanime should be fixed.

### Actual Result

zoro source won't work and since it is the only source to watch anime on , it should get fixed. gogoanime stopped working a long time ago

### Device Information

Saikou Version : 1.2.3.0
Brand : Amazon
Android Version : 9

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Please try to fix this sooner

**Comment by brahmkshatriya** [comment] 2023-07-06 11:10
Duplicate of #724

**Closed by brahmkshatriya** 2023-07-06 11:10 UTC
Labels: bug
