### ISSUE TITLE
Better discovery and search for anime and manga.

### ISSUE THREAD

**Issue by cheesuscrisp** [saikou-app/saikou#331] opened 2022-07-22 09:01 UTC
### Summary

Suggestion to add sort by completed, and multiple genres at once, both by exclusion and by inclusion.

### The Problem

Currently, search is not very functional, as you can only filter by 1 genre at a time, only by inclusion. I understand this is a pre-release app, and I LOVE THIS APP SO MUCH, but I also think it could benefit with better search, hence the suggestion, unless already planned.

### The Ideal Solution

My ideal solution would be to have an [AL-chan](https://github.com/zend10/AL-chan) like front end or search, filter and discovery function, in the saikou design aesthetic, which I really like.
It would be even better to have an option to fetch data for search from AniList, MyAnimeList, or MangaUpdates (I think this might be difficult because they don't have a public API), but I don't know if thats possible.

### The Current Solution

Currently, we can only filter by 1 genre, only by exclusion, eg. we can only filter by "Romance", and it will show all manga sorted however, which have romance listed as a genre in AniList.

**Comment by brahmkshatriya** [comment] 2022-07-22 13:27
duplicate of #146

**Closed by brahmkshatriya** 2022-07-22 13:27 UTC
Labels: enhancement
