### ISSUE TITLE
Streams aren't working  

### ISSUE THREAD

**Issue by Iamroni25** [saikou-app/saikou#562] opened 2023-02-19 13:40 UTC
### Summary

Stream aren't showing in any servers                

### Reproduction Steps

Idk

### Expected Result

I expect to happen that streams would appear but it didn't 

### Actual Result

When I click on episode it usually pops up and let you choos server like vidstream. But after update it doesn't show anything like that and says there's an error

### Device Information

Saikou Version: 1.2.0.24
Device: Redmi selene
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

Pls fix this

**Comment by brahmkshatriya** [comment] 2023-02-19 14:37
duplicate of https://github.com/saikou-app/saikou/issues/559

**Closed by brahmkshatriya** 2023-02-19 14:37 UTC
Labels: bug

**Comment by Iamroni25** [comment] 2023-02-20 08:44
Yes exactly like #559

**Comment by edgehub-cloud** [comment] 2023-02-20 09:25
Make the streams break Harder daddy.

**Comment by Lakshya5088** [comment] 2023-02-20 10:12
> Make the streams break Harder daddy.

Aw hell naw 🗿

**Comment by ShivamB25** [comment] 2023-02-20 10:13
sooooo hoooot
