### ISSUE TITLE
Source not working 

### ISSUE THREAD

**Issue by savioben** [saikou-app/saikou#729] opened 2023-07-06 07:14 UTC
### Summary

Zoro.to and all anime not working 

### Reproduction Steps

Please make it work

### Expected Result

To work

### Actual Result

Not working 

### Device Information

Saikou Version: 1.2.3.0
Device: POCO bhima
Architecture: aarch64
OS Version: REL 13 (33)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment] 2023-07-06 11:10
Duplicate of #724

**Closed by brahmkshatriya** 2023-07-06 11:10 UTC
Labels: bug
